[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "find . -name 'test_func_inspect_special_encoding.py' -delete || true",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn app:app"